#!/bin/bash
#
# post-receive hook
#
# Add comments in the jira tickets using jira API.
# When the git push is received, every commit adds a comment depending on the jira tickets found in the commit message.
# The jira comment contains :
# - SHA1 commit
# - Commit author
# - Commit date
# - Commit message
#
# This file must be named post-receive, and be saved in the hook directory in a bare git repository.
# Run "chmod +x post-receive" to make it executable.
#
# Don't forget to change the jira server url, jira id regex, login and password, and git service url
#
# GitHub: https://github.com/FabreFrederic/git-hook-post-receive-jira-message
# 
echo
echo "post-receive git hook"
echo

jiraBeginUrl="http://jira.yourserver.com/rest/api/2/issue"
jiraEndUrl="comment"
jiraIdRegex="[a-zA-Z]{3}-[0-9]{1,6}"

# Jira credentials
jiraLogin="login@server.com"
jiraPassword="password"

# Your Git service url like github, gogs, ...
# You have to put "/" at the end
gitServiceUrl="http://gitservice.com/myrepository/commit/"

# Branchs loop
# because it is possible to push more than one branch at a time with the "git push --all" command
while read oldrev newrev refname
do
    echo "Processing branch : $refname"
    echo "--------------------------------------------------------"

    # Commits loop
    for sha1Commit in $(git rev-list --reverse $oldrev..$newrev)
    do
        # The comment is the text after the first blank line
        gitComment=$(git cat-file commit $sha1Commit | sed '1,/^$/d')
        jiraIds=$(echo $gitComment | grep -Po $jiraIdRegex)

        # Jira tickets loop
        for jiraId in ${jiraIds[@]}
        do 
            echo "Processing Jira ticket : $jiraId"
            jiraComment=$(git show -s --format=medium $sha1Commit)
	    
            # Add git branch name
            jiraComment="Git branch : $refname\n$jiraComment"
            
	    # Add git comment on a new line
	    jiraComment=$(echo $jiraComment | sed "s/$gitComment//g")
            jiraComment="$jiraComment\n\n$gitComment"

            # Escaping characters
            jiraComment=$(echo $jiraComment | sed 's/\n/\\n/g')
            jiraComment=$(echo $jiraComment | sed 's/\b//g')
            jiraComment=$(echo $jiraComment | sed 's/\r/\\r/g')
	    jiraComment=$(echo $jiraComment | sed 's/\t/\\t/g')
            jiraComment=$(echo $jiraComment | sed 's/"/\"/g')
            jiraComment=$(echo $jiraComment | sed "s/'/\\'/g")
            
            # Author and date on a new line
            jiraComment=$(echo $jiraComment | sed 's/Author:/\\nAuthor:/g')
            jiraComment=$(echo $jiraComment | sed 's/Date:/\\nDate:/g')

	    # Add git service url link
            gitServiceUrl=$gitServiceUrl$sha1Commit
            jiraComment=$jiraComment\\n\\n$gitServiceUrl
                       
	    # Uncomment to debug
            #echo "debug begin"
	    #echo $jiraComment
	    #echo
	    #echo $jiraBeginUrl+"/"+$jiraId+"/"+$jiraEndUrl
            #echo
	    #curl -D- -u $jiraLogin:$jiraPassword -X POST --data "{\"body\": \"test post-receive git hook\"}" -H "Content-Type: application/json" $jiraBeginUrl/$jiraId/$jiraEndUrl
	    #echo "debug end"
		
	    # All errors will be ignored
            curl -D- -u $jiraLogin:$jiraPassword -X POST --data "{\"body\": \"$jiraComment\"}" -H "Content-Type: application/json" $jiraBeginUrl/$jiraId/$jiraEndUrl > /dev/null 2>&1
            echo "New message added in the Jira ticket"
            echo
        done
    done
done

echo
echo "post-receive git hook : see you soon"
exit 0
